apiVersion: v1
kind: Namespace
metadata:
  name: dream-home-11
  labels:
    name: dream-home-11
    environment: production
    app.kubernetes.io/name: dream-home-11
    app.kubernetes.io/part-of: dream-home-11
