apiVersion: v1
kind: Service
metadata:
  name: dream-home-11-green
  namespace: dream-home-11
  labels:
    app.kubernetes.io/name: dream-home-11
    app.kubernetes.io/component: backend
    app.kubernetes.io/deployment: green
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: dream-home-11
    app.kubernetes.io/component: backend
    app.kubernetes.io/deployment: green
